# Generated by Django 5.0.6 on 2024-06-25 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Заголовок")),
                ("slug", models.CharField(max_length=20, verbose_name="slug")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="содержимое"),
                ),
                (
                    "preview",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="blog/image",
                        verbose_name="превью (изображение)",
                    ),
                ),
                (
                    "created_at",
                    models.DateField(
                        auto_now_add=True, verbose_name="Дата создания (записи в БД)"
                    ),
                ),
                ("publication", models.BooleanField(verbose_name="Публикация поста")),
                (
                    "views_counter",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Проказывает кол-во просмотров",
                        verbose_name="Счётчик просмотров",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пост",
                "verbose_name_plural": "Посты",
                "ordering": ["title", "slug", "publication"],
            },
        ),
    ]
