# Generated by Django 5.0.6 on 2024-06-23 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="views_counter",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Проказывает кол-во просмотров",
                verbose_name="Счётчик просмотров",
            ),
        ),
    ]
