# Generated by Django 5.0.6 on 2024-07-06 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_product_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Version",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version_number",
                    models.PositiveIntegerField(default=0, verbose_name="Номер версии"),
                ),
                ("version_name", models.TextField(verbose_name="Название версии")),
                ("current_version", models.BooleanField(verbose_name="Текущая версия")),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="Продукт",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Версия",
                "verbose_name_plural": "Версия",
                "ordering": [
                    "product",
                    "version_number",
                    "version_name",
                    "current_version",
                ],
            },
        ),
    ]
