# Generated by Django 5.0.6 on 2024-07-07 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_version"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.CharField(
                blank=True, null=True, verbose_name="Описание продукта"
            ),
        ),
    ]
